# Gym Env
env_name: "gym_examples/contGrid-v5"
state_dim: 3
action_dim: 1
action_range: [0, 6.28318]
F: 1
vel_field: "/home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/data/GPT_dset_DG3/static_obs/GPTdset_DG3_g100x100x120_r5k_Obsv1_25305"
del_t: 1. 
scale_velocity: False
vmax_by_F: 1
space_scale: 1
target_radius: 2
rtg_scale: 100
add_transition_noise_during_inf: False
noise_var: [0.1,0]

# Paths
log_dir: "log"
dataset_name: "GPT_DG3"
# dataset_path: "/media/HDD/rohit/Translation_transformer/my-translat-transformer/data/GPT_dset_DG3/static_obs/GPTdset_DG3_g100x100x120_r5k_Obsv1_scaled_0.7_multi_ran_stat_new/Gathered_datasets/gathered_5_100_327_withr/gathered_5_100_327_withr.pkl"
# params2_name: "/media/HDD/rohit/Translation_transformer/my-translat-transformer/data/GPT_dset_DG3/static_obs/GPTdset_DG3_g100x100x120_r5k_Obsv1_scaled_0.7_multi_ran_stat_new/Gathered_datasets/gathered_5_100_327_withr/params.yml"
dataset_path: "/media/HDD/rohit/Translation_transformer/my-translat-transformer/data/GPT_dset_DG3/static_obs/GPTdset_DG3_g100x100x120_r5k_Obsv1_scaled_0.7_multi_ran_stat_new/Gathered_datasets/gathered_3_100_2872_withr/gathered_3_100_2872_withr.pkl"
params2_name: "/media/HDD/rohit/Translation_transformer/my-translat-transformer/data/GPT_dset_DG3/static_obs/GPTdset_DG3_g100x100x120_r5k_Obsv1_scaled_0.7_multi_ran_stat_new/Gathered_datasets/gathered_3_100_2872_withr/params.yml"

# mae_model_name: "/media/HDD/rohit/Translation_transformer/my-translat-transformer/mae_logs/GPT_MAE/Sept23_100envs_cosw_randomr_hs_168E/Bestuned_fbMae_Model_5000D_168E.pt"
# mae_model_name: "/media/HDD/rohit/Translation_transformer/my-translat-transformer/mae_logs/GPT_MAE/Sept23_100envs_cosw_randomr_hs_1000E/Bestuned_fbMae_Model_5000D_1000E.pt"
# env_decoder_name: "/home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/log/EmbFcast_DG3_model_11-09-09-19.pt/best_vloss.pt"
tae_model_arch: "/home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/tiny_ae_logs/Nov23_100envs_clr_randomr/finetuned_tinyautoenc_500D_100E/arch.pt"
tae_state_dict: "/home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/tiny_ae_logs/Nov23_100envs_clr_randomr/finetuned_tinyautoenc_500D_100E/best_vloss.pt"
env_predictor_name: "/home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/log/EmbFcast_DG3_model_11-24-11-07.pt"


# Dataset
random_split: True
split_tr_tst_val: [0.7, 0.1, 0.2]
split_ran_seed: 42
num_workers: 4

# Training
device: 'cuda'
batch_size: 16
loss_type: 'mean_norm_of_vec_diff'      #'mean_norm_of_vec_diff' or "mse_over_angle"
optimizer_name: 'AdamW'
num_epochs: 60
lr: 0.0005 #0.001
final_lr: 0.00005
wt_decay: 0.01
dropout_p: 0.1
break_training: 200
grad_clip: 100
# add_target_loss: False
# warmup_steps: 10000

use_scheduler: True
stepLR_stepsize: 10

# Architecture
pos_encoding_type: 'simple' # simple or sin
num_encoder_layers: 3
num_decoder_layers: 3
context_len: 123
embed_dim: 240
n_heads: 8

# Save and Evaluate
eval_inerval: 2
chkpt_interval: 5
chkpt_list: []
translate_earlybreaks: [2, 2, 2] #tr, test, val

desired_rtg: 60  # TODO: can we do something smarter with the reward sequence?

# Vizualization
viz_input: False
sim_tgt_actions: False # works only if viz_input is True
viz_break_at: 100




# preprocessor: 'ViT_scratch'
# vit_scratch config
# hidden_size_vit: 128 = emb_dim
# num_hidden_layers_vit: 2
# num_attention_heads_vit: 4
# intermediate_size_vit: 256
# image_size_vit: 224
# patch_size_vit: 16
# num_channels_vit: 2
# hidden_dropout_prob_vit: 0.0
# attention_probs_dropout_prob_vit: 0.0
# 4 4 32


# num_eval_ep: 200
# a_tl: 1000
# req_context_len: 36
# 