F: 0.115
action_activation: sigmoid
action_dim: 1
action_range:
- 0
- 6.28318
add_target_loss: false
add_transition_noise_during_inf: false
batch_size: 32
break_training: 200
cheat_RTG: true
chkpt_interval: 25
chkpt_list: []
context_len: 63
dataset_name: Perlin
dataset_path: /media/HDD/rohit/Translation_transformer/my-translat-transformer/data/Perlin/Gathered_datasets_paths/gathered_7_100_withr_nm40_new/gathered_7_100_withr_nm40_new.pkl
del_t: 1
desired_rtg: 60
device: cuda
dropout_p: 0
embed_dim: 96
env_name: gym_examples/contGrid-v5_2
env_predictor_name: /home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/log/EmbFcast_Perlin_model_03-19-13-56.pt
eval_inerval: 2
final_lr: 1.0e-05
grad_clip: 10
log_dir: log
loss_type: mean_norm_of_vec_diff
lr: 0.01
matmul_precision: high
n_heads: 12
noise_var:
- 0.1
- 0
num_decoder_layers: 8
num_encoder_layers: 8
num_epochs: 200
num_workers: 4
optimizer_name: AdamW
params2_name: ' '
plot_grads_k_freq_ep_intvl:
- 1
- 5
pos_encoding_type: simple
random_split: true
rtg_scale: 100
scale_velocity: true
sim_tgt_actions: false
space_scale: 1
split_ran_seed: 40
split_tr_tst_val:
- 0.7
- 0.1
- 0.2
src_LN_in_dataloader: true
state_dim: 3
stepLR_stepsize: 1
target_radius: 2
translate_earlybreaks:
- 2
- 2
- 2
use_fabric: false
use_scheduler: true
vel_field: /home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/data/DG3/raw_data/nT_120
viz_break_at: 100
viz_input: false
vmax_by_F: 1.174
warmup_steps: 10000
wb_id: o9x2fojy
wt_decay: 0
